package store

import (
	"context"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/Kekzim/sommelierskill/internal/normalize"
)

// norm reduces a value to a comparable string, so a Go argument and whatever
// SQLite handed back can be compared without caring which of int64/float64/
// []byte the driver chose.
func norm(v any) string {
	switch x := v.(type) {
	case nil:
		return "NULL"
	case bool:
		if x {
			return "1"
		}
		return "0"
	case *int:
		if x == nil {
			return "NULL"
		}
		return strconv.Itoa(*x)
	case *float64:
		if x == nil {
			return "NULL"
		}
		return strconv.FormatFloat(*x, 'g', -1, 64)
	case int:
		return strconv.Itoa(x)
	case int64:
		return strconv.FormatInt(x, 10)
	case float64:
		return strconv.FormatFloat(x, 'g', -1, 64)
	case []byte:
		return string(x)
	case string:
		return x
	default:
		return "?"
	}
}

// distinct returns a product whose every field carries a different value, so a
// column that receives the wrong argument is visible rather than coincidentally
// equal.
func distinct() normalize.Product {
	p := sample()
	p.ProductNumber = "pn"
	p.Supplier = "supplier"
	p.Country = "Frankrike"
	p.Origin1 = "Bordeaux"
	p.Origin2 = "Médoc"
	p.Cat3 = "Kraftigt"
	p.CategoryTitle = "Rött vin"
	p.Vintage = i(2019)
	p.SugarPer100ML = f64(1.5)
	p.IsOrganic = true
	p.IsEthical = true
	p.EthicalLabel = "Fairtrade"
	p.Packaging = "Flaska"
	p.Seal = "Naturkork"
	p.CO2Impact = "0.9"
	p.ClockSweetness = i(2)
	p.ClockBitter = i(3)
	p.ClockFruitacid = i(8)
	p.ClockSmokiness = i(1)
	p.ClockCasque = i(4)
	p.CasqueText = "Ek"
	p.Color = "Djupt rubinröd"
	p.Usage = "Serveras vid 18°C"
	p.LaunchDate = "2026-09-11T00:00:00"
	p.SellStartTime = "10:00:00"
	p.IsNews = true
	p.IsWebLaunch = true
	p.AssortmentCode = "TSE"
	return p
}

// The upsert's column list, its placeholders and its argument slice are all
// generated by walking productColumns. This proves they walk it the same way:
// every column is read back by NAME and compared with the argument its value
// function produced, so a builder that lists columns in one order and arguments
// in another is caught rather than quietly storing the producer in `country`.
//
// What it does not catch is a value function reading the wrong field of
// normalize.Product -- both sides of the comparison come from that function, so
// they agree either way. That is a typo in a one-line literal, visible on
// reading, and it was the risk before this change too. The ordering is the part
// that is now machine-generated and therefore worth a machine check.
func TestUpsertArgumentsLineUpWithColumns(t *testing.T) {
	p := distinct()
	db := openTemp(t)
	put(t, db, p)

	for _, c := range insertable() {
		var got any
		if err := db.SQL().QueryRow(
			`SELECT "` + c.name + `" FROM product WHERE product_id = '1'`).Scan(&got); err != nil {
			t.Fatalf("selecting %s: %v", c.name, err)
		}
		if want := norm(c.value(p)); norm(got) != want {
			t.Errorf("product.%s = %q, want %q -- the upsert's arguments are out of step with its column list",
				c.name, norm(got), want)
		}
	}
}

// The snapshot is where a column goes missing without anything failing: it has
// its own CREATE TABLE and its own SELECT list, and a column absent from both
// is not an error, just an unanswerable question. `launch_date` lived in
// `product` for months and never reached the snapshot, so the app-side skill
// could not answer anything about release dates.
//
// Both are now generated from the `slim` field, and this proves it end to end --
// by value, not just by name, so a reordered SELECT is caught too.
func TestSnapshotCarriesEverySlimColumn(t *testing.T) {
	p := distinct()
	db := openTemp(t)
	put(t, db, p)

	path := filepath.Join(t.TempDir(), "snapshot.db")
	if _, err := db.ExportSlim(context.Background(), path, 2); err != nil {
		t.Fatalf("ExportSlim: %v", err)
	}
	snap, err := OpenExisting(path)
	if err != nil {
		t.Fatalf("OpenExisting(snapshot): %v", err)
	}
	defer snap.Close()

	for _, c := range slimColumns() {
		var got any
		if err := snap.SQL().QueryRow(
			`SELECT "` + c.name + `" FROM product WHERE product_id = '1'`).Scan(&got); err != nil {
			t.Fatalf("snapshot is missing %s: %v", c.name, err)
		}
		// Generated columns have no value function; their correctness is
		// TestRoundTripAndGeneratedColumns' job. Everything else must arrive
		// with the value it was stored with.
		if c.value == nil {
			continue
		}
		if want := norm(c.value(p)); norm(got) != want {
			t.Errorf("snapshot product.%s = %q, want %q", c.name, norm(got), want)
		}
	}
}

// The specific miss that started this: a release date in the mirror has to be
// answerable from the snapshot the skill actually ships with.
func TestSnapshotAnswersReleaseDates(t *testing.T) {
	db := openTemp(t)
	put(t, db, distinct())

	path := filepath.Join(t.TempDir(), "snapshot.db")
	if _, err := db.ExportSlim(context.Background(), path, 2); err != nil {
		t.Fatalf("ExportSlim: %v", err)
	}
	snap, err := OpenExisting(path)
	if err != nil {
		t.Fatalf("OpenExisting: %v", err)
	}
	defer snap.Close()

	var n int
	if err := snap.SQL().QueryRow(`
		SELECT count(*) FROM product
		WHERE substr(launch_date,1,10) = '2026-09-11' AND assortment_code = 'TSE'`).Scan(&n); err != nil {
		t.Fatalf("querying the snapshot for a release: %v", err)
	}
	if n != 1 {
		t.Errorf("the snapshot matched %d products dropping on 2026-09-11, want 1", n)
	}
}

// Every column that is not generated and not the primary key must be reachable
// by migration, or an existing database can never gain it.
func TestEveryColumnIsMigratableOrExplained(t *testing.T) {
	for _, c := range productColumns {
		if c.generated != "" || c.key {
			continue
		}
		// ALTER TABLE ADD COLUMN refuses NOT NULL without a DEFAULT, so such a
		// column could only ever exist in a freshly created database.
		ddl := c.ddl
		if strings.Contains(ddl, "NOT NULL") && !strings.Contains(ddl, "DEFAULT") {
			switch c.name {
			case "name", "raw", "synced_at":
				// Present since the first schema; no database lacks them.
			default:
				t.Errorf("product.%s is NOT NULL without a DEFAULT, so migration cannot add it "+
					"to an existing database", c.name)
			}
		}
	}
}
